#!/bin/bash

IMG=${IMG:-"mpsocks.img"}
DIR="mount_${IMG}"

build_image() {
	qemu-img create $IMG 10g
	mkfs.ext3 $IMG
	mkdir $DIR
	sudo mount -o loop $IMG $DIR

	git clone https://salsa.debian.org/installer-team/debootstrap.git
	sudo DEBOOTSTRAP_DIR=$(pwd)/debootstrap ./debootstrap/debootstrap --arch amd64 stretch $DIR

	sudo chroot $DIR passwd root

	# auto up our mgmt interface
	#TODO check EOF when rerun, due to align change
	sudo bash -c "grep -q enp0s3 $DIR/etc/network/interfaces || 
	cat >> $DIR/etc/network/interfaces <<EOF

auto enp0s3
allow-hotplug enp0s3
iface enp0s3 inet dhcp
EOF"

	# install SSH and our key.

	sudo chroot $DIR apt-get install -y openssh-server --allow-unauthenticated
	sudo mkdir $DIR/root/.ssh
	sudo chmod 700 $DIR/root/.ssh
	sudo bash -c "cat $HOME/.ssh/id_rsa.pub >> $DIR/root/.ssh/authorized_keys"
	sudo chmod 600 $DIR/root/.ssh/authorized_keys

	# TODO integrate this, i did this to cancel the default route learn over dhcp for mgmt
	# we won't use it.
	# cat /etc/dhcp/dhclient-exit-hooks.d/drop_default
	# if [ "${reason}" = "BOUND" -a "${interface}" = "enp0s3" ] ; then
	#         if [ "$(ip r | grep default | awk '{print $3}')" = "${new_routers}" ] ; then
	#                 ip route del default
	#         fi
	# fi
	sudo umount $DIR
	rmdir $DIR
}

build_kernel() {
	git clone https://github.com/multipath-tcp/mptcp.git
	cd mptcp
	make O=build-kvm x86_64_defconfig
	make O=build-kvm kvmconfig

	scripts/config --file build-kvm/.config --enable MPTCP
	scripts/config --file build-kvm/.config --enable MPTCP_PM_ADVANCED
	scripts/config --file build-kvm/.config --enable MPTCP_FULLMESH
	scripts/config --file build-kvm/.config --enable MPTCP_NDIFFPORTS
	scripts/config --file build-kvm/.config --enable MPTCP_BINDER
	scripts/config --file build-kvm/.config --enable MPTCP_NETLINK
	scripts/config --file build-kvm/.config --enable DEFAULT_FULLMESH
	scripts/config --file build-kvm/.config --set-str DEFAULT_MPTCP_PM "fullmesh"
	scripts/config --file build-kvm/.config --enable MPTCP_SCHED_ADVANCED
	scripts/config --file build-kvm/.config --enable MPTCP_BLEST
	scripts/config --file build-kvm/.config --enable MPTCP_ROUNDROBIN
	scripts/config --file build-kvm/.config --enable MPTCP_REDUNDANT
	scripts/config --file build-kvm/.config --enable DEFAULT_SCHEDULER
	scripts/config --file build-kvm/.config --set-str DEFAULT_MPTCP_SCHED "default"

	scripts/config --file build-kvm/.config --disable RETPOLINE

	make O=build-kvm olddefconfig
	make O=build-kvm -j 8
	cd -
}

configure_host_tap() {
	sudo ip tuntap add mode tap user $(whoami) name mptcp
	sudo ip address add 6.6.6.1/24 dev mptcp
	sudo ip l set dev mptcp up
}

configure_host_tap2() {
	sudo ip tuntap add mode tap user $(whoami) name mptcp2
	sudo ip address add 6.6.7.1/24 dev mptcp2
	sudo ip l set dev mptcp2 up
}

clean_host_tap() {
	sudo ip link del mptcp
}

clean_host_tap2() {
	sudo ip link del mptcp2
}

ssh_vm() {
	ssh -o "UserKnownHostsFile /dev/null" -o "StrictHostKeyChecking no" -p 6222 root@localhost $@
}

ssh_vm_pseudoterm() {
	ssh -t -o "UserKnownHostsFile /dev/null" -o "StrictHostKeyChecking no" -p 6222 root@localhost $@
}

configure_guest_nw() {
	ssh_vm ip addr add 6.6.6.2/24 dev enp0s4
	ssh_vm ip link set dev enp0s4 up
	ssh_vm ip route del default
	ssh_vm ip route add default via 6.6.6.1
}

configure_guest_nw2() {
	ssh_vm ip addr add 6.6.7.2/24 dev enp0s5
	ssh_vm ip link set dev enp0s5 up
	ssh_vm ip rule add from 6.6.7.2 table 666
	ssh_vm ip route add default via 6.6.7.1 table 666
}

configure_host_nat() {
	sudo iptables -t nat -A POSTROUTING -s 6.6.6.2/32 -j MASQUERADE
	sudo iptables -A FORWARD -i mptcp -j ACCEPT
	sudo iptables -A FORWARD -o mptcp -j ACCEPT
}

clean_host_nat() {
	sudo iptables -t nat -D POSTROUTING -s 6.6.6.2/32 -j MASQUERADE
	sudo iptables -D FORWARD -i mptcp -j ACCEPT
	sudo iptables -D FORWARD -o mptcp -j ACCEPT
}

configure_host_nat2() {
	sudo iptables -t nat -A POSTROUTING -s 6.6.7.2/32 -j MASQUERADE
	sudo iptables -A FORWARD -i mptcp2 -j ACCEPT
	sudo iptables -A FORWARD -o mptcp2 -j ACCEPT
}

clean_host_nat2() {
	sudo iptables -t nat -D POSTROUTING -s 6.6.7.2/32 -j MASQUERADE
	sudo iptables -D FORWARD -i mptcp2 -j ACCEPT
	sudo iptables -D FORWARD -o mptcp2 -j ACCEPT
}

# $1 where to get out from src routing
configure_host_source_routing() {
	sudo ip rule add iif mptcp2 table 666
	local gw=$(ip route | grep default | grep $1 | awk '{ print $3}')
	sudo ip route add default via $gw table 666
}

clean_host_source_routing() {
	sudo ip rule del iif mptcp2 table 666
	sudo ip route del default table 666
}

check_mptcp() {
	# wget into an identity crisis obviously
	ssh_vm wget -O- -U curl multipath-tcp.org 2>/dev/null
}

run_ssh_socks() {
	ssh -o "UserKnownHostsFile /dev/null" -o "StrictHostKeyChecking no" -p 6222 -D 6666 -N  root@localhost
}

run_socks() {
	echo "^C to kill it !"
	local method=${1:-ssh}
	run_${method}_socks
}

install_dante() {
	ssh_vm ip r del default
	ssh_vm ip r add default via 10.0.2.2
	ssh_vm apt-get install -y --allow-unauthenticated build-essential
	ssh_vm mkdir tools
	ssh_vm "wget -O- https://www.inet.no/dante/files/dante-1.4.2.tar.gz | tar -ixz --directory tools"
	ssh_vm "cd tools/dante-1.4.2 && ./configure && make"
}

run_dante_socks() {
	cat <<'EOF' | ssh_vm "cat - > /tmp/sockd.conf"
logoutput: stderr

internal: 6.6.6.2 port = 6666

external: 6.6.6.2

socksmethod: none

client pass {
        from: 6.6.6.0/24 port 1-65535 to: 0.0.0.0/0
}

socks pass {
        from: 6.6.6.0/24 to: 0.0.0.0/0
        protocol: tcp udp
}
EOF
	ssh_vm_pseudoterm tools/dante-1.4.2/sockd/sockd -f /tmp/sockd.conf
}

boot_vm() {
	qemu-system-x86_64 -m 512 -kernel ./mptcp/build-kvm/arch/x86/boot/bzImage -hda $IMG -append "root=/dev/sda rw console=ttyS0" --enable-kvm --nographic -device e1000,netdev=mgmt -device e1000,netdev=network0 -netdev tap,id=network0,ifname=mptcp,script=no,downscript=no -netdev user,id=mgmt,hostfwd=tcp:127.0.0.1:6222-:22
}

boot_vm2() {
	qemu-system-x86_64 -m 512 -kernel ./mptcp/build-kvm/arch/x86/boot/bzImage -hda $IMG -append "root=/dev/sda rw console=ttyS0" --enable-kvm --nographic -device e1000,netdev=mgmt -device e1000,netdev=network0 -netdev tap,id=network0,ifname=mptcp,script=no,downscript=no -netdev user,id=mgmt,hostfwd=tcp:127.0.0.1:6222-:22 -device e1000,netdev=network1 -netdev tap,id=network1,ifname=mptcp2,script=no,downscript=no
}
